### PR TITLE
Returns message if no files of the size are found

### PR DESCRIPTION
**Pull request by abea**
I think I ran into a situation where the size noted didn't exist but it ran and output the count anyway. This would communicate that the size doesn't exist yet.

### CODE REVIEW

**Comment by abea** [comment]
Maybe this isn't necessary. You wouldn't get the count output, so my particular case probably isn't addressed by this. It could be an enhancement, though, so I'll leave this open for now.

**Comment by abea** [comment]
@boutell I came across this older one. Would it be good to go with a change to the apos logging utility?

**Comment by boutell** [comment]
It's a standalone CLI tool, not a real Apostrophe module, so console.log/console.warn/console.error is appropriate.

**Comment by boutell** [comment]
I merged it, feel free to publish it.

**Pull request merged**
